# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='idno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
