# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0002_participant_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BITSians',
            fields=[
                ('idno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=4)),
                ('room', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered', models.BooleanField(default=False)),
            ],
        ),
    ]
