# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registrations', '0003_bitsians'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitsians',
            options={'ordering': ('idno',), 'verbose_name': 'BITSian', 'verbose_name_plural': 'BITSians'},
        ),
    ]
